### ISSUE TITLE
Create save and load system

### ISSUE THREAD

**Issue by Gir3245** [UQdeco2800/2021-studio-3#166]
# Description
Design way to save and load a player's data, specifically from a pre-designated checkpoint which is defined in the level scope. After arriving at a checkpoint, the player's stats (lives, health, sprint, etc.) are all saved. When accessed from the load screen that will be created associatively, the user will respawn at this point. The saving system implemented in this feature will utilize a save file, to which the player's info will be saved to and retrieved, upon access. The current design of this system will encompass a single save file, however multiple save files will be considered if feasible.

# Sub-features / components
- Implementation of load screen from which save file will be accessible
- Implementation of save file functionality
- Re-Implementation of checkpoint feature for each level

# Milestones
- [x] Create Documentation - 07/10
- [x] #172
- [x] #173
- [x] #174
- [x] Merge to main #244 
- [x] Update Documentation - 17/10

# Documentation
- [Save and Load System](https://github.com/UQdeco2800/2021-studio-3/wiki/Save-and-Load-System)

**Comment by K0zzas17** [comment]
Save and Load system is complete.
