### ISSUE TITLE
Lives not reducing on Level Two & Three Bug

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#183]
# Description
With the addition of multiple maps in the previous sprint, the lives system was not maintained across the additional levels (Level Two, Level Three). 

**Related Task**:  (#171)

# Milestones
- [x] Update current implementation to allow lives to decrease on the additional levels

# Members
(@K0zzas17 )

**Comment by K0zzas17** [comment]
A yes I see, I fixed the bug but I will leave it on the lives_all_levels branch in case you or others wanted to see access the fix.

Do you think your changes will impact how #166 might be designed?? Or can we safely proceed with our implementation?
