### ISSUE TITLE
Player movement animation bug 

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#266]
# Description
When the player goes into the level two, three and four, at the beginning point of each level, the player movement animation does not work at all. The movement animation will go back to normal after the player character moves a long distance.

Related feature (#22 )
# Member

**Comment by default-jamc** [comment]
This also happens on level one. #265

**Comment by Dollar0712** [comment]
Fixed by adding a new variable is isPause to check the level state of the game
